name: Regression Priority Tests

on:
  workflow_dispatch:

jobs:
  run-tests:
    name: Build and Execute Regression Priority Tests
    runs-on: ubuntu-latest

    env:
      HEADLESS_MODE: "true"
      DISPLAY: ":99"
      SE_CACHE_PATH: "${{ runner.temp }}/something"

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Print cache path
        run: echo "$SE_CACHE_PATH"

      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Verify Maven
        run: mvn -version

      - name: Set Up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Verify Chrome
        run: google-chrome --version

      - name: Run Regression Priority Tests
        run: mvn test
